import { getCurrency } from '@divzy/shared';

/**
 * WI-068 §3 — helpers for the MoneyText count-up ticker.
 *
 * The ticker runs on the reanimated UI thread (non-editable TextInput +
 * useAnimatedProps), where `formatMoney` cannot be called: it is a plain JS
 * function using `Intl.NumberFormat`, and worklets can neither invoke
 * JS-thread closures nor rely on Intl in the worklet runtime. Instead:
 *
 * 1. `moneyTickerDescriptor` (JS thread) probes Intl via `formatToParts` and
 *    captures the currency/locale's shape as a plain serializable object —
 *    prefix/suffix for positive AND negative, group + decimal separators,
 *    grouping sizes (incl. Indian lakh grouping and min-grouping-digits
 *    quirks), and fraction digits.
 * 2. `formatTickerText` (worklet-safe, pure integer/string math — no Intl,
 *    no floats) renders any minor-unit value against that descriptor.
 *
 * Parity contract: `formatTickerText(minor, moneyTickerDescriptor(code))`
 * must equal `formatMoney(minor, code)` byte-for-byte — enforced by
 * `motion.test.ts` across every supported currency. MoneyText additionally
 * pins the FINAL frame to the exact `formatMoney` string, so the resting
 * figure can never drift even on an exotic locale.
 *
 * (Motion timing/easing constants live in `@/theme` — `motion`, `easing`,
 * `spring`, `pressScale` — not here; reduced-motion detection is reanimated's
 * `useReducedMotion()`. This module exists so the ticker math stays pure and
 * Node-testable.)
 */

export interface MoneyTickerDescriptor {
  /** Fraction digits (currency decimals). */
  decimals: number;
  /** Group separator ('' = locale never groups). */
  group: string;
  /** Decimal separator. */
  decimal: string;
  /** Rightmost group size (3 in western formats). */
  primaryGroup: number;
  /** Subsequent group size (3 western, 2 Indian). */
  secondaryGroup: number;
  /** Minimum integer digits before grouping applies (es-ES: 5 → "1000" ungrouped). */
  minGroupedDigits: number;
  posPrefix: string;
  posSuffix: string;
  negPrefix: string;
  negSuffix: string;
}

interface AffixScan {
  prefix: string;
  suffix: string;
  intSizes: number[];
  group: string;
  decimal: string;
}

function scanParts(parts: Intl.NumberFormatPart[]): AffixScan {
  let prefix = '';
  let suffix = '';
  let group = '';
  let decimal = '.';
  const intSizes: number[] = [];
  let seenNumber = false;
  for (const part of parts) {
    if (part.type === 'integer') {
      seenNumber = true;
      intSizes.push(part.value.length);
    } else if (part.type === 'group') {
      group = part.value;
    } else if (part.type === 'decimal') {
      decimal = part.value;
    } else if (part.type === 'fraction') {
      // digits themselves — regenerated by the ticker
    } else if (!seenNumber) {
      prefix += part.value;
    } else {
      suffix += part.value;
    }
  }
  return { prefix, suffix, intSizes, group, decimal };
}

/**
 * Derive the format descriptor for a currency/locale on the JS thread.
 * Mirrors `formatMoney`'s fallback (`symbol` + `toFixed`) when Intl rejects
 * the currency, so parity holds on both paths.
 */
export function moneyTickerDescriptor(currency: string, locale?: string): MoneyTickerDescriptor {
  const info = getCurrency(currency);
  const decimals = info.decimals;
  try {
    const nf = new Intl.NumberFormat(locale, {
      style: 'currency',
      currency: info.code,
      minimumFractionDigits: decimals,
      maximumFractionDigits: decimals,
    });
    const pos = scanParts(nf.formatToParts(1234567890));
    const neg = scanParts(nf.formatToParts(-1234567890));
    const sizes = pos.intSizes;
    const primaryGroup = sizes.length > 1 ? sizes[sizes.length - 1]! : 3;
    const secondaryGroup = sizes.length > 2 ? sizes[sizes.length - 2]! : primaryGroup;
    // Locales like es-ES leave 4-digit integers ungrouped (minimumGroupingDigits 2).
    const fourDigit = scanParts(nf.formatToParts(1000));
    const minGroupedDigits = pos.group === '' ? 0 : fourDigit.intSizes.length > 1 ? 4 : 5;
    return {
      decimals,
      group: pos.group,
      decimal: pos.decimal,
      primaryGroup,
      secondaryGroup,
      minGroupedDigits,
      posPrefix: pos.prefix,
      posSuffix: pos.suffix,
      negPrefix: neg.prefix,
      negSuffix: neg.suffix,
    };
  } catch {
    // formatMoney's catch renders `${symbol}${major.toFixed(decimals)}`;
    // for negatives toFixed puts the minus AFTER the symbol ("$-12.30").
    return {
      decimals,
      group: '',
      decimal: '.',
      primaryGroup: 3,
      secondaryGroup: 3,
      minGroupedDigits: 0,
      posPrefix: info.symbol,
      posSuffix: '',
      negPrefix: `${info.symbol}-`,
      negSuffix: '',
    };
  }
}

/**
 * Render integer minor units against a descriptor. Worklet-safe: pure
 * integer/string math, callable on the reanimated UI thread every frame.
 */
export function formatTickerText(minor: number, desc: MoneyTickerDescriptor): string {
  'worklet';
  const rounded = Math.round(minor);
  const negative = rounded < 0;
  let digits = String(Math.abs(rounded));
  while (digits.length < desc.decimals + 1) digits = `0${digits}`;
  const intDigits = desc.decimals > 0 ? digits.slice(0, digits.length - desc.decimals) : digits;
  const fracDigits = desc.decimals > 0 ? digits.slice(digits.length - desc.decimals) : '';

  let grouped = intDigits;
  if (desc.group !== '' && intDigits.length >= desc.minGroupedDigits) {
    const chunks: string[] = [];
    let rest = intDigits;
    let size = desc.primaryGroup;
    while (rest.length > size) {
      chunks.unshift(rest.slice(rest.length - size));
      rest = rest.slice(0, rest.length - size);
      size = desc.secondaryGroup;
    }
    chunks.unshift(rest);
    grouped = chunks.join(desc.group);
  }

  const number = desc.decimals > 0 ? `${grouped}${desc.decimal}${fracDigits}` : grouped;
  return negative
    ? `${desc.negPrefix}${number}${desc.negSuffix}`
    : `${desc.posPrefix}${number}${desc.posSuffix}`;
}
